// Default configuration for Sahab Budget

const DEFAULT_CATEGORY_CONFIG = {
    Housing: {
        keywords: ['RENT', 'MORTGAGE', 'WILLOW GLEN', 'APARTMENT', 'LEASE'],
        color: '#FF6384',
        icon: '🏠',
        description: 'Rent, mortgage, and housing expenses',
    },
    Groceries: {
        keywords: [
            'COSTCO',
            'WALMART',
            'TARGET',
            'KROGER',
            'SAFEWAY',
            'WHOLE FOODS',
            'TRADER JOE',
            'ALDI',
        ],
        color: '#36A2EB',
        icon: '🛒',
        description: 'Grocery shopping and household items',
    },
    Transportation: {
        keywords: ['BP', 'SHELL', 'CHEVRON', 'GAS', 'FUEL', 'UBER', 'LYFT', 'PARKING', 'TOLL'],
        color: '#FFCE56',
        icon: '🚗',
        description: 'Gas, parking, and transportation',
    },
    'Food & Dining': {
        keywords: [
            'RESTAURANT',
            'PIZZA',
            'BURGER',
            'CAFE',
            'COFFEE',
            'STARBUCKS',
            'DUNKIN',
            'DINING',
        ],
        color: '#4BC0C0',
        icon: '🍕',
        description: 'Restaurants, cafes, and dining out',
    },
    Shopping: {
        keywords: ['AMAZON', 'AMZN', 'EBAY', 'MALL', 'STORE', 'SHOP'],
        color: '#9966FF',
        icon: '🛍️',
        description: 'Online and retail shopping',
    },
    Subscriptions: {
        keywords: [
            'NETFLIX',
            'SPOTIFY',
            'APPLE',
            'GOOGLE',
            'AMAZON PRIME',
            'HULU',
            'DISNEY',
            'CHATGPT',
            'CLAUDE',
        ],
        color: '#FF9F40',
        icon: '📱',
        description: 'Monthly subscriptions and services',
    },
    Insurance: {
        keywords: ['STATE FARM', 'GEICO', 'ALLSTATE', 'INSURANCE', 'PROGRESSIVE'],
        color: '#FF6384',
        icon: '🛡️',
        description: 'Insurance payments',
    },
    Healthcare: {
        keywords: ['PHARMACY', 'CVS', 'WALGREENS', 'DOCTOR', 'MEDICAL', 'HOSPITAL', 'DENTAL'],
        color: '#C9CBCF',
        icon: '🏥',
        description: 'Medical and healthcare expenses',
    },
    Entertainment: {
        keywords: [
            'MOVIE',
            'THEATER',
            'CONCERT',
            'GAME',
            'SPORT',
            'GYM',
            'FITNESS',
            'PLANET FITNESS',
        ],
        color: '#4BC0C0',
        icon: '🎬',
        description: 'Entertainment and leisure activities',
    },
    'Personal Care': {
        keywords: ['SALON', 'BARBER', 'SPA', 'BEAUTY', 'HAIRCUT', 'NAILS', 'GREAT CLIPS'],
        color: '#FF6384',
        icon: '💅',
        description: 'Personal care and grooming',
    },
    Utilities: {
        keywords: [
            'ELECTRIC',
            'WATER',
            'GAS BILL',
            'INTERNET',
            'ATT',
            'VERIZON',
            'COMCAST',
            'ATT*BILL',
        ],
        color: '#36A2EB',
        icon: '💡',
        description: 'Utility bills and services',
    },
    Phone: {
        keywords: ['VISIBLE', 'T-MOBILE', 'VERIZON WIRELESS', 'AT&T WIRELESS'],
        color: '#95A5A6',
        icon: '📞',
        description: 'Phone bills and services',
    },
    Others: {
        keywords: [],
        color: '#95A5A6',
        icon: '📦',
        description: 'Uncategorized expenses',
    },
};

const DEFAULT_BUDGET_TEMPLATES = {
    Conservative: {
        total: 2500,
        categories: {
            Housing: 900,
            Groceries: 400,
            Transportation: 250,
            'Food & Dining': 200,
            Shopping: 150,
            Subscriptions: 100,
            Others: 500,
        },
    },
    Moderate: {
        total: 3500,
        categories: {
            Housing: 1200,
            Groceries: 500,
            Transportation: 350,
            'Food & Dining': 400,
            Shopping: 300,
            Subscriptions: 150,
            Others: 600,
        },
    },
    Comfortable: {
        total: 5000,
        categories: {
            Housing: 1800,
            Groceries: 600,
            Transportation: 500,
            'Food & Dining': 600,
            Shopping: 500,
            Subscriptions: 200,
            Others: 800,
        },
    },
};

const APP_CONFIG = {
    appName: 'Sahab Budget',
    company: 'Sahab Solutions',
    version: '1.0.0',
    currency: 'USD',
    currencySymbol: '$',
    dateFormat: 'MM/DD/YYYY',
    chartColors: [
        '#FF6384',
        '#36A2EB',
        '#FFCE56',
        '#4BC0C0',
        '#9966FF',
        '#FF9F40',
        '#FF6384',
        '#C9CBCF',
        '#4BC0C0',
        '#FF6384',
    ],
};
